### ISSUE TITLE
Building the documentation fails

### ISSUE THREAD

**Issue by bit-pirate** [wg-perception/object_recognition_core#18]
When following the instructions to build the documentation at http://wg-perception.github.io/object_recognition_core/install.html#install, I can't execute the last step `make doc`, since there is no target to be build.

`make doxygen` already creates some documentation, which can be found for example in `.../build/object_recognition_core/api/html`. However, I can't find pages like install, quickguide etc.

**Comment by Abduoit** [comment]
Hi,
I am trying to install object-recognition-kitchen-tabletop. When I do make sphinx-doc in ~/ork/build/$
I get this error, anyone can help plz???

imr@IMR-PC:~/ork/build$ make sphinx-doc
Running Sphinx v1.6.2
SYS.PATH=== ['/usr/local/bin', '/home/imr/ork/devel/lib/python2.7/dist-packages', '/opt/ros/indigo/lib/python2.7/dist-packages', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gst-0.10', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode', '/home/imr/ork/src/tabletop/doc/source']
/usr/local/lib/python2.7/dist-packages/sphinx/util/requests.py:64: UserWarning: Some links may return broken results due to being unable to check the Server Name Indication (SNI) in the returned SSL cert against the hostname in the url requested. Recommended to install "requests[security]" as a dependency or upgrade to a python version with SNI support (Python 3 and Python 2.7.9+).
  'Some links may return broken results due to being unable to '
WARNING: sphinx.ext.pngmath has been deprecated. Please use sphinx.ext.imgmath instead.
WARNING: unknown config value 'ecto_docs_dir' in override, ignoring

Theme error:
no theme named 'ecto_theme' found (missing theme.conf?)
make[3]: *** [object_recognition_tabletop-sphinx] Error 1
make[2]: *** [tabletop/CMakeFiles/object_recognition_tabletop-sphinx.dir/all] Error 2
make[1]: *** [ecto_ros/CMakeFiles/sphinx-doc.dir/rule] Error 2
make: *** [sphinx-doc] Error 2

**Comment by hris2003** [comment]
As mentioned above, you need to make sure that you have ecto package in your ork workspace too. For the best result, use rosinstall file ([instructions](http://wg-perception.github.io/object_recognition_core/install.html#rosinstall-file)) to have everything pulled to your workspace.

**Comment by Abduoit** [comment]
Hi Ha, thx for reply please tell me where I am wrong
 
I tried to install ork on both ros kinetic on ubuntu 16.04. and ros indigo ubuntu 14.04, but I could not fix it.
I did the following steps but still I couldn't find ork-table-top on the rviz.

`mkdir -p ork/src && cd ork/src`
`export DISTRO=indigo
sudo apt-get install libopenni-dev ros-${DISTRO}-catkin ros-${DISTRO}-ecto* ros-${DISTRO}-opencv-candidate ros-${DISTRO}-moveit-msgs
source /opt/ros/${DISTRO}/setup.sh`
`git clone http://github.com/wg-perception/object_recognition_core
git clone http://github.com/wg-perception/capture
git clone http://github.com/wg-perception/reconstruction
git clone http://github.com/wg-perception/linemod
git clone http://github.com/wg-perception/ork_renderer
git clone http://github.com/wg-perception/tabletop
git clone http://github.com/wg-perception/tod
git clone http://github.com/wg-perception/transparent_objects`
`git clone http://github.com/wg-perception/object_recognition_msgs
git clone http://github.com/wg-perception/object_recognition_ros
git clone http://github.com/wg-perception/object_recognition_ros_visualization`
`cd ../ && catkin_make`

**Comment by hris2003** [comment]
These steps are to compile ORK on your machine. To run tabletop and view its result, you need to follow the [tabletop tutorial](https://wg-perception.github.io/ork_tutorials/tutorial02/tutorial.html).

**Comment by Abduoit** [comment]
Thx 
I went through this tutorial, I can NOT find ork-tabletop on rviz I can't add it

**Comment by hris2003** [comment]
Well, then, it's not here to post the issue or question. Please either send email to the ork group or open an issue of tabletop tutorial, and please list of the steps that you do so that others can replicate the situation, thus eventually find a solution. Thanks.
