### ISSUE TITLE
'object_recognition_core detect'  throws error

### ISSUE THREAD

**Issue by YuOhara** [wg-perception/object_recognition_core#30]
I am flowing the quick start guide, but when I try detection_command, the program stops.
the error was
python: /usr/include/boost/smart_ptr/shared_ptr.hpp:418: T\* boost::shared_ptr<T>::operator->() const [with T = const sensor_msgs::Image_std::allocator<void >]: Assertion `px != 0' failed.

https://groups.google.com/forum/#!topic/object-recognition-kitchen/mEW0Vn2NreM also reports the same problem.
I use openni_launch, but the object_recognition_core program always says the same error.

**Comment by shomberg** [comment]
Hi,

I'm also trying to follow the quick start guide to use ORK with ROS and I'm running into the same error.

Running openni_launch seems to be working and the camera is publishing to the appropriate topics.  rviz can access and use them just fine.

I've verified that my ros-indigo-ecto package is at version 0.6.7 and ros-indigo-ecto-ros is at 0.4.5.  I've tried installing and re-installing from compiled ros packages as well as compiling the ROS packages from source as detailed on the install page, with the same results.

I tried again today with the new version 0.4.6 of ros-indigo-ecto-ros and I get the same result.

Is there anything else which could be causing this problem?

**Comment by vrabaud** [comment]
can you please try with the latest from ecto (the problem was on the ecto side, not ecto_ros side). It's version 0.6.8.
What do you launch exactly ? Does it crash too if you launch any of those scripts ?
https://github.com/plasmodic/ecto_opencv/tree/master/samples/rgbd

**Comment by shomberg** [comment]
Hi,

For my previous tests I was following the quickstart guide by running:
roslaunch openni_launch openni_launch
rosrun object_recognition_capture orb_template -o my_textured_plane

The second command gave the assertion failed error.

I tried those scripts you mention while ecto 0.6.7 was still installed.  I was unable to get consistent results - sometimes some of them would run, sometimes they would give the same error as before with the failed assert.

I uninstalled 0.6.7 and attempted to build 0.6.8 from source (because it is not yet in the ROS repositories for Ubuntu) and again tried to run the scripts.  One of them worked once, but all the other times it failed on a seg-fault immediately after printing the initial "Registration? 1 Sync? 0".  It is possible something got messed up when I was installing from source though or from some interaction with the old version from the repositories.

**Comment by windonground** [comment]
For my tests I was following the quickstart guide by running:
roslaunch openni_launch openni_launch
rosrun object_recognition_capture orb_template -o my_textured_plane
Then it crashes with these lines:
Listening for key: s on imshow:save
Registration? 1
Sync? 0
python: /usr/include/boost/smart_ptr/shared_ptr.hpp:646: typename boost::detail::sp_dereference<T>::type boost::shared_ptr<T>::operator*() const [with T = xn::NodeInfo; typename boost::detail::sp_dereference<T>::type = xn::NodeInfo&]: Assertion `px != 0' failed.
Aborted (core dumped)

Then I go through other tests,  "rosrun object_recognition_capture orb_template -o my_textured_plane" crashs too if I launch any of those scripts in: https://github.com/plasmodic/ecto_opencv/tree/master/samples/rgbd

I am also sure the following topics ( * /camera/depth/camera_info[sensor_msgs/CameraInfo] * /camera/rgb/image_raw [sensor_msgs/Image]* /camera/depth/image_raw [sensor_msgs/Image] * /camera/rgb/camera_info [sensor_msgs/CameraInfo]
) is publishing messages!

Does any body have explanations about this type of exceptions?? Thanks for any suggestions :)

I use the latest ecto (0.6.8) and ecto_ros (0.4.6) under ros indigo version. My computer run the ubuntu 1404 32bit system. Besides,  SensorKinect is installed to make openni_launch work with Kinect.

**Comment by vrabaud** [comment]
are you using openni or openni2 ?

**Comment by pelferina** [comment]
Where/how can I remap the topics being subscribed to by the object_recognition, if at all?

**Comment by awesomebytes** [comment]
@pelferina When you run the server you give it a config file right?
Like at the tutorial:
http://wg-perception.github.io/ork_tutorials/tutorial02/tutorial.html

Doing:
    rosrun object_recognition_core detection -c `rospack find object_recognition_tabletop`/conf/detection.table.ros.ork

In that config file (https://github.com/wg-perception/tabletop/blob/master/conf/detection.table.ros.ork ) you specify the topics.

I hope that helps.

**Comment by windonground** [comment]
@vrabaud 
I am using openni, not openni2.At this point, I really followed the quick guide.
Do you mean I should use openni2? Because I see openni2_launch in some other tutorials in ork...

**Comment by pelferina** [comment]
Thank you! That really helped a lot!

**Comment by nosepas1** [comment]
Hi, 

I don't know if the problem is already fixed but I'm trying to follow the quickguide and the tutorials and I have some problems!
When I try quickguide I have the same problem as everyone:
_rosrun object_recognition_capture orb_template -o my_textured_plane
Listening for key: s on imshow:save
Registration? 1
Sync? 0
python: /usr/include/boost/smart_ptr/shared_ptr.hpp:646: typename boost::detail::sp_dereference<T>::type boost::shared_ptr<T>::operator*() const [with T = xn::NodeInfo; typename boost::detail::sp_dereference<T>::type = xn::NodeInfo&]: Assertion `px != 0' failed.
Aborted_
could anyone help me please?

Then, I have try to detect objects using tabletop and everything works well but when I have to the detect the object I have this error:
_rosrun object_recognition_core detection -c  `rospack find object_recognition_tabletop`/conf/detection.object.ros.ork

[ INFO] [1457369669.064329642]: Initialized ROS. node_name: /object_recognition_server
[ INFO] [1457369669.342392025]: System already initialized. node_name: /object_recognition_server
[ INFO] [1457369669.807556971]: System already initialized. node_name: /object_recognition_server
[ INFO] [1457369669.818679779]: Subscribed to topic:/camera/depth_registered/camera_info [queue_size: 1][tcp_nodelay: 0]
[ INFO] [1457369669.825657466]: Subscribed to topic:/camera/rgb/camera_info [queue_size: 1][tcp_nodelay: 0]
[ INFO] [1457369669.831797794]: Subscribed to topic:/camera/depth_registered/image_raw [queue_size: 1][tcp_nodelay: 0]
[ INFO] [1457369669.840060002]: Subscribed to topic:/camera/rgb/image_color [queue_size: 1][tcp_nodelay: 0]
126 :: 0.5 , 1 , 0.995004 , /base_link , /head_mount_kinect_rgb_optical_frame
[ INFO] [1457369670.616131299]: publishing to topic:/tabletop/clusters
[ INFO] [1457369670.617674595]: publishing to topic:/table_array
Loading model: 3571bc74fb68200cdb7d7bed2e000263 for object id: YOUR_OBJECT_IDInfo,  T0: Load 
Error, T0: Unable to open file "".
Segmentation fault_
Any idea about that?

I use the latest ecto (0.6.11) and ecto_ros (0.4.8) under ros indigo distribution. 
Many thanks

**Comment by hris2003** [comment]
@nosepas1 : For your first question: Are you sure that the output of your camera is working? Can you visualize its topics in ROS with rostopic echo <topic_name>? 
And your second issue is because there's no mesh file in your database, maybe because the capture phase didnot succeed...

**Comment by nosepas1** [comment]
@hris2003 : The first issue it's true that I have some problems with the topics, many thanks. 

The second issue, I have add the mesh manually, I have capture nothing. And when I look in my db the mesh is there. Could it be something else? 

Thank you!

**Comment by nosepas1** [comment]
@hris2003 : When I use freenect instead of openni all the topics are working well but the capture doesn't. Can I use freenect or it is no compatibility?

**Comment by hris2003** [comment]
@nosepas1 Which mesh did you add to the database? The coke mesh? Or did you prepare it yourself? Can I have a look at the mesh?

**Comment by nosepas1** [comment]
@hris2003 I added the coke mesh from the tutorial

**Comment by saspelund** [comment]
♫ This is the thread that never ends! Oh it goes on and on my friends! ♫

Error: `OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /build/buildd/opencv-2.4.8+dfsg1/modules/imgproc/src/color.cpp, line 3648`

I can't find the code/file (/build doesn't exist in my root directory) to see where the error is happening to try to fix it. I have read multiple forum posts about this error, but they all suggest edits to the code which I can't do as I can't find the source file (`locate` didn't help either). [They](http://stackoverflow.com/questions/20822288/python-opencv-cv2-opencv-error-assertion-failed-scn-3-scn-4-in-unkno) say that this error means that the number of channels is incorrect. However, I have checked that all four of the topics are publishing using rostopic echo+info as well as being able to stream the images (cameras) in rviz.

Here is my gdb ouput. The line in question occurs after the subscribe to topics + thread exits.

```
~/catkin_ws/src/ork/src/object_recognition_core/apps$ gdb --args python ./detection -c `rospack find object_recognition_tod`/conf/detection.ros.ork --visualize
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/bin/python ./detection -c /home/<username>/catkin_ws/src/ork/src/tod/conf/detection.ros.ork --visualize
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
/home/<username>/catkin_ws/devel/lib/python2.7/dist-packages/ecto/__init__.py:30: RuntimeWarning: to-Python converter for boost::shared_ptr<ecto::tendril> already registered; second conversion method ignored.
  del os_path
/home/<username>/catkin_ws/devel/lib/python2.7/dist-packages/ecto/__init__.py:30: RuntimeWarning: to-Python converter for boost::shared_ptr<ecto::cell> already registered; second conversion method ignored.
  del os_path
/home/<username>/catkin_ws/devel/lib/python2.7/dist-packages/ecto/__init__.py:30: RuntimeWarning: to-Python converter for boost::shared_ptr<ecto::py::cellwrap> already registered; second conversion method ignored.
  del os_path
[New Thread 0x7fffd8f86700 (LWP 16987)]
[New Thread 0x7fffd32a3700 (LWP 16993)]
[New Thread 0x7fffd2aa2700 (LWP 16994)]
[New Thread 0x7fffd22a1700 (LWP 16995)]
[New Thread 0x7fffd1aa0700 (LWP 17000)]
[New Thread 0x7fffd129f700 (LWP 17001)]
[New Thread 0x7fffd0a9e700 (LWP 17002)]
[New Thread 0x7fffc3fff700 (LWP 17003)]
[New Thread 0x7fffc37fe700 (LWP 17004)]
[ INFO] [1466443762.601328756]: Initialized ROS. node_name: /object_recognition_server
[ INFO] [1466443763.119278958]: System already initialized. node_name: /object_recognition_server
[ INFO] [1466443764.000748594]: System already initialized. node_name: /object_recognition_server
[New Thread 0x7fffaffff700 (LWP 17013)]
[New Thread 0x7fffaf7fe700 (LWP 17014)]
[New Thread 0x7fffaeffd700 (LWP 17015)]
[New Thread 0x7fffae7fc700 (LWP 17017)]
[ INFO] [1466443764.019444709]: Subscribed to topic:/camera/depth/camera_info [queue_size: 1][tcp_nodelay: 0]
[Thread 0x7fffaffff700 (LWP 17013) exited]
[ INFO] [1466443764.029586662]: Subscribed to topic:/camera/rgb/camera_info [queue_size: 1][tcp_nodelay: 0]
[Thread 0x7fffaf7fe700 (LWP 17014) exited]
[ INFO] [1466443764.045366795]: Subscribed to topic:/camera/rgb/image_raw [queue_size: 1][tcp_nodelay: 0]
[Thread 0x7fffae7fc700 (LWP 17017) exited]
[ INFO] [1466443764.055873076]: Subscribed to topic:/camera/depth/image_raw [queue_size: 1][tcp_nodelay: 0]
[Thread 0x7fffaeffd700 (LWP 17015) exited]
OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /build/buildd/opencv-2.4.8+dfsg1/modules/imgproc/src/color.cpp, line 3648
Traceback (most recent call last):
  File "./detection", line 24, in <module>
    run_plasm(args, plasm)
  File "/home/<username>/catkin_ws/src/ecto/python/ecto/opts.py", line 85, in run_plasm
    sched.execute(options.niter)
ecto.CellException:            exception_type  CellException
[cell_name] = source1

[cell_type] = ecto::py::BlackBox

[function_name] = process_with_only_these_inputs

[type] = std::runtime_error

[what] =            exception_type  CellException
[cell_name] = Source

[cell_type] = ecto::py::BlackBox

[function_name] = process_with_only_these_inputs

[type] = std::runtime_error

[what] =            exception_type  CellException
[cell_name] = ecto_ros::Image2Mat

[cell_type] = ecto_ros::Image2Mat

[function_name] = process_with_only_these_inputs

[type] = cv::Exception

[what] = /build/buildd/opencv-2.4.8+dfsg1/modules/imgproc/src/color.cpp:3648: error: (-215) scn == 3 || scn == 4 in function cvtColor
...
[Thread 0x7fffd1aa0700 (LWP 17000) exited]
[Thread 0x7fffd32a3700 (LWP 16993) exited]
[Thread 0x7fffd2aa2700 (LWP 16994) exited]
[Thread 0x7fffd0a9e700 (LWP 17002) exited]
[Thread 0x7fffc37fe700 (LWP 17004) exited]
[Thread 0x7fffd129f700 (LWP 17001) exited]
[Thread 0x7fffc3fff700 (LWP 17003) exited]
[Thread 0x7fffd8f86700 (LWP 16987) exited]
[Thread 0x7fffd22a1700 (LWP 16995) exited]
[Inferior 1 (process 16980) exited with code 01]
(gdb) 
```

According to Nosepas1's error output, the next line after the subscriber thread exits should read 
`'126 :: 0.5 , 1 , 0.995004 , /base_link , /head_mount_kinect_rgb_optical_frame'`

If this thread is better asked elsewhere, please tell me where. Thanks for your help!

**Comment by saspelund** [comment]
I fixed my error by changing the subscribed topic in the tod config file (see the above response from vraboud to pelferina) for the rgb_image_topic from `/camera/rgb/image_raw` to `/camera/rgb/image_color`. I believe that this fixed the issue because the code was expecting a colored (3 channel=rgb) or color+alpha (4 channels) matrix (or the 3rd dimension of the matrix is either 3 or 4 deep but at least there is one rather than only 2 dimensions with a grey scale value at each point) and was only getting a grey scale image from image_raw.

Hopefully this helps anyone who runs into this problem! Now off to figure out why the program won't accept my uploaded coke can mesh during detection......

**Comment by NearXdu** [comment]
Hi～ I just got the same problem , when i'm run
```
roslaunch openni_launch openni_launch
rosrun object_recognition_capture orb_template -o my_textured_plane
```
Listening for key: s on imshow:save
Registration? 1
Sync? 0
python: /usr/include/boost/smart_ptr/shared_ptr.hpp:646: typename boost::detail::sp_dereference::type boost::shared_ptr::operator*() const [with T = xn::NodeInfo; typename boost::detail::sp_dereference::type = xn::NodeInfo&]: Assertion `px != 0' failed.
Aborted (core dumped)

how could I solve this?  I test this under my `ubuntu14.04 64bits ros-indigo`, and the camera is `microsoft kinect v1`

**Comment by jinjuehui** [comment]
> Listening for key: s on imshow:save
> Registration? 1
> Sync? 0
> 
>  python: /usr/include/boost/smart_ptr/shared_ptr.hpp:641: typename boost::detail::sp_dereference<T>::type boost::shared_ptr<T>::operator*() const [with T = xn::NodeInfo; typename boost::detail::sp_dereference<T>::type = xn::NodeInfo&]: Assertion `px != 0' failed.
> Aborted (core dumped)

also get involved in the same problem, anyone solved it yet?

**Comment by jinjuehui** [comment]
In my case it worked after I `killall XnSensorServer` after `roslaunch openni_launch openni.launch`. might helpful to uninstall the driver `sudo apt-get remove libopenni-sensor-pointclouds0` if there are two devices detected.
